### ISSUE TITLE
Надо как-то отмечать offline участников планирования

### ISSUE THREAD

**Issue by LDC7** [DirectumCompany/Yotalab.PlanningPoker#19]
Может менять аватарку?
+ сортировать, чтобы офлайн участники были внизу.

**Comment by hankir** [comment]
Для начала надо сделать, чтобы вообще можно было понять, что участник онлайн или офлайн :)
Нужен хелс чек, а отмечать можно по классике - зеленый кружок, серый кружок

**Comment by sinking-dying** [comment]
Во время планирования все на связи же? Можно сказать: "Алло, %username%, ты тут?")

**Comment by hankir** [comment]
> Во время планирования все на связи же? Можно сказать: "Алло, %username%, ты тут?")

Точно, и кнопочку добавить - если нажал, значит онлайн, и по таймеру статус сбрасывать, чтобы периодически нажимал)
Ручной хелс чек

**Comment by LDC7** [comment]
я думал можно как-то подписаться на события сигналР'а, который используется Блазором, но что-то не могу найти как это сделать.
