### ISSUE TITLE
Добавить возможность исключения участника из сессии планирования

### ISSUE THREAD

**Issue by hankir** [DirectumCompany/Yotalab.PlanningPoker#3]
В карточке сессии добавить возможность удалить участника из голосования

Критерии:
- Действие удаления участника - участник может повторно присоединиться к голосованию
- Вариация удаления участника - с блокировкой входа (бан)

**Comment by LDC7** [comment]
Взялся
PR #8

**Comment by LDC7** [comment]
кажется бан можно отложить, если не вообще вырезать.
Вроде не очень нужная функция.
