### ISSUE TITLE
Сакральный смысл кнопки остановить?

### ISSUE THREAD

**Issue by MfalmeWaWafu** [DirectumCompany/Yotalab.PlanningPoker#37]
Сначала нажимаю остановить, потом ещё надо завершить, чтобы начать заново. Увидеть оценки каждого перед общей статистикой? Их можно враз показывать :)

**Comment by hankir** [comment]
@MfalmeWaWafu 
Остановить - останавливает процесс голосования, после этого команда обсуждает голоса. Может быть большой разброс по голосам - значит не все понимают оцениваемую задачу одинаково. Возможно кто-то изменит свою оценку, на этапе остановленной сессии это еще можно сделать. После того, как консенсус найден, голосование завершается и выводится результат.
