### ISSUE TITLE
Изменение названия сессии в остановленном голосовании сбрасывает оценки участников

### ISSUE THREAD

**Issue by TimerbaevRR** [DirectumCompany/Yotalab.PlanningPoker#39]
Когда участники сессии проголосовали и голосование остановлено, смена названия сессии приведёт к сбросу оценок участников.
Возможно, при завершённом голосовании тоже сбрасывается, пока нет возможности проверить.

**Comment by hankir** [comment]
Исправлено в 44d9485da618d6b19a2c1bfa6c36f1372b0bf3c6
